# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: rootuser
  password: ""

development:
  <<: *default

  database: tech_blog_development

test:
  <<: *default
  database: tech_blog_test

production:
  <<: *default
  database: tech_blog_production
  url: <%= ENV['DATABASE_URL'] %>